apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user
    spec:
      containers:
      - image: sjc.vultrcr.com/oosa/app-user:v1.0.0
        name: user
        livenessProbe:
          httpGet:
            path: /health/alive
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: APP_PORT
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: APP_PORT
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: DB_CONNECTION
        - name: DB_API_DATABASE
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: DB_API_DATABASE
        - name: CLOUDFLARE_IMAGE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: CLOUDFLARE_IMAGE_AUTH_TOKEN
        - name: CLOURDLARE_IMAGE_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: CLOURDLARE_IMAGE_ACCOUNT_ID
        - name: CLOURDLARE_IMAGE_ACCOUNT_HASH
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: CLOURDLARE_IMAGE_ACCOUNT_HASH
        - name: CLOURDLARE_IMAGE_DELIVERY_URL
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: CLOURDLARE_IMAGE_DELIVERY_URL
        - name: FRIEND_LIST_LIMIT
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: FRIEND_LIST_LIMIT
        - name: MINIMUM_TOP_RANKING
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: MINIMUM_TOP_RANKING
        - name: SSO_REGISTER_URL
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: SSO_REGISTER_URL
        - name: SESSION_STORE_TYPE
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: SESSION_STORE_TYPE
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: SESSION_SECRET
        - name: SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: SESSION_KEY
        - name: SESSION_PSQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: SESSION_PSQL_CONNECTION_STRING
        - name: APP_BASE_URL
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: APP_BASE_URL
      volumes:
        - name: user-secrets
          secret:  
            secretName: user-secrets