---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: dev-build-docker-image
  commands:
  - docker build -t oosa-user:dev .
- name: restart service
  commands:
  - docker-compose -f docker-dev.yml down
  - docker container prune -f
  - docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
  - docker-compose -f docker-dev.yml up -d

trigger:
  branch:
  - dev
...