---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: test-build-docker-image
  commands:
  - docker build -t oosa-user:dev .
- name: restart service
  commands:
  - docker-compose -f docker-test.yml down
  - docker-compose -f docker-test.yml up -d

trigger:
  branch:
  - test
...